version: '3'
services:
  node:
    image: buyanse/nodejs:latest
    container_name: server
    restart: always
    build: .
    ports:
      - "5050:5050"
    environment:
      - SERVER_PORT=5050
      - SERVER_MORGAN=tiny

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: